[package]
name = "verkle-spec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum-types = "0.13.1"
verkle-trie = { path = "../verkle-trie", default-features = false }
hex = "0.4"